# Generated by Django 6.0.1 on 2026-05-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_configuracionsistema_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='modulo',
            field=models.CharField(choices=[('categorias', 'Categorías'), ('productos', 'Productos'), ('usuarios', 'Usuarios'), ('servicios', 'Servicios')], max_length=20),
        ),
    ]
