# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0006_configuracionsistema_historial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="destacado",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
