# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0007_producto_destacado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historial",
            name="modulo",
            field=models.CharField(
                choices=[
                    ("categorias", "Categorías"),
                    ("productos", "Productos"),
                    ("servicios", "Servicios"),
                    ("usuarios", "Usuarios"),
                ],
                max_length=20,
            ),
        ),
    ]
