# Generated by Django 6.0.1 on 2026-05-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='productos_por_pagina',
            field=models.IntegerField(default=8),
        ),
    ]
