# Generated by Django 6.0.1 on 2026-05-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_configuracionsistema_productos_por_pagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confianza',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='icon',
            field=models.CharField(max_length=50),
        ),
    ]
