# Generated by Django 6.0.1 on 2026-05-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_alter_confianza_icon_alter_publicacion_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasoproceso',
            name='numero',
            field=models.CharField(max_length=50),
        ),
    ]
