# Generated by Django 6.0.1 on 2026-05-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_publicacion_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
